mongodb/intellij

CHANGELOG.md
gradle/diktat.yml
gradle/libs.versions.toml
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MdbJavaEditorToolbar.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProvider.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/i18n/Icons.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/i18n/MdbToolbarMessages.kt
packages/jetbrains-plugin/src/main/resources/icons/GreenCircle.svg
packages/jetbrains-plugin/src/main/resources/messages/MdbToolbarBundle.properties
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecoratorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProviderTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/javaEditor/JavaDriverToolbarVisibilityUiTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/FixtureExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MongoDbEnvironmentTestExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/UiTestExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/idea/IdeaFrame.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/TelemetryServiceTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/ConnectionFailureProbeTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
packages/mongodb-access-adapter/datagrip-access-adapter/build.gradle.kts
packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/IntegrationTest.kt
packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriverTest.kt

feat: allow to attach a data source to a java editor

---

packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/IntegrationTest.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtilTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFieldReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt
packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NodeTest.kt

chore: basic parser for queries with the java driver INTELLIJ-19

---

packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/MdbPluginDisposable.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/PersistentToolbarSettings.kt

Came across this while testing INTELLIJ-83. We were persisting settings per application level and not per project. This PR fixes that and now we will be persisting settings per project level

fix: for persisting datastore selection for a workspace between IntelliJ sessions INTELLIJ-83

---

.github/workflows/draft-release.yaml
build.gradle.kts

chore: instead of running the whole pipeline again, only allow drafts when main is green already

---

.github/workflows/quality-check.yaml
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DataSourceComboBox.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DatabaseComboBox.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/MongoDbRunQueryActionUiTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/javaEditor/JavaDriverToolbarVisibilityUiTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/AssertionExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/FixtureExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/InfoAndProgressPanelFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MdbStepLogger.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/RightToolWindowHeaderFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/UiTestExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/DatabaseToolWindowFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/GradleToolWindowFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbActionGutterFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/MdbJavaEditorToolbarPopupFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/RightToolbarFixture.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/idea/IdeaFrame.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/settings/SettingsUiTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/build.gradle.kts
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/settings.gradle.kts
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/NoDriverReference.java
packages/jetbrains-plugin/src/test/resources/video.properties

Two things that I identified inducing flakiness in our UI tests were:
1. ComboBox getting updated while tests were trying to use them, made the combobox collapse
2. Tests were not able to recover from unexpected state and eventually failed
To address the first concern, we are now updating the combobox only when there is an actual change, otherwise not and that too wrapped in an invokeLater so that existing interactions are finished before performing the update.
Second concern is addressed in two steps:
1. We do not want to interact with the comboboxes, right after they show up on screen because they subscribe to the StateFlow and eventually a state update follows which leads to the disruption in UI interaction. So we have put a short timeout of 1 second to allow for initial state …

chore: improvements on flakiness of UI tests INTELLIJ-107

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/BsonTypeTest.kt

When using a $in filter, it is expected to provide a List of string/number, etc to be matched against a field which itself is a simple type (string/number, etc). This PR marks such assignment acceptable so that our linter does not throw false positive warnings.

fix: makes a List assignable to simple type INTELLIJ-120

---

packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MdbJavaEditorToolbar.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecoratorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModelTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt

There is another variant of Filters.eq which only accepts single parameter. In that case, the FieldReference is static and pointing to _id. This commit adds support for parsing this variant.

feat: support for single parameter eq INTELLIJ-108

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/NamespaceCheckingLinter.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/adt/Either.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/adt/EitherInclusive.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/Parser.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasCollectionReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasFieldReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasFilter.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasSourceDialect.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasUpdates.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasValueReference.kt

A Parser is a suspendable function that returns either an error or a valid output from a
lazy input. Parsers can be composed using different functions, like filter, map, mapError...
All these compositions return a new Parser.
To understand how a parser works, we need to think that parsers are a pipeline: the output of this parser is
the input of the next parser.
Parser are typesafe on input, error and output.
Some examples, let's say we want to get the collection reference, if it's know, on a query. We
would define the parser as the following:
```kt
val knownCollRef = knownCollectionReference<S>();
```
Note how we specify S in the knownCollectionReference parser. It's because S is generic in our
model. This will return a parser of the following type:
```kt
Parser<Node<S>, …
```

poc(parser): parser combinator poc

---

packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt

There were two issues happening:
1. PsiMethodCallExpression/s like `MongoCollection.find(Filters.eq("name", "MongoDb")).first()` were supposed to be mapped to `FIND_ONE` but were getting mapped to `FIND_MANY`.
2. With correctly mapped FIND_ONE, the parser was not able to resolve the filters from the PsiMethodCallExpression because the valid expression at that point is from `MongoIterable` class and not from `MongoCollection` class.
This PR fixes the above two issues by:
1. Correctly mapping FIND_ONE when identified
2. Resolving the filters from correct method call expression given an identified command

fix: fixes parsing of FindIterable.first call expression

---

packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriverTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
packages/mongodb-dialects/spring-@query/src/test/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParserTest.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/IndexAnalyzer.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Node.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFieldReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFilter.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasUpdates.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasFieldReference.kt
packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/IndexAnalyzerTest.kt
packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NodeTest.kt

Just pulling out the refactor that is harmless (rename of FieldReference.Known to FieldReference.FromSchema) and touches multiple files. Part of work required in INTELLIJ-125

chore: rename HasFieldReference.(Known to FromSchema) and introduce HasChildren interface INTELLIJ-125

---

packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshBackendTest.kt
packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/IsCommand.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/Parser.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasAggregation.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/Named.kt

feat: Index checking for aggregates that start with $match INTELLIJ-139

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/AggregationParserTest.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/MatchStageParserTest.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/ProjectStageParserTest.kt
packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Node.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasProjections.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasFieldReference.kt

Includes:
- Parsing of $project built with Aggregates.project, limited to, as defined in scope:
- Projections.include
- Projections.exclude
- Projections.fields
- Autocomplete support for fields in Projections.include, Projections.exclude and Projections.fields
- Linter inspections for field existence and type checks in Projections

feat: adds support for parsing Aggregates.project stage INTELLIJ-126

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/MatchStageParserTest.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/ProjectStageParserTest.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/SortStageParserTest.kt
packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasSorts.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt

Includes:
- Parsing of $sort built with Aggregates.sort, limited to, as defined in scope:
- Sorts.ascending
- Sorts.descending
- Sorts.orderBy
- Autocomplete support for fields in Sorts.ascending, Sorts.exclude and Sorts.orderBy
- Linter inspections for field existence and type checks in Sorts
I noticed that we were not parsing incomplete match calls so added that here as well ([eac0239](https://github.com/mongodb/intellij/pull/97/commits/eac0239e56c35a3fff6ed1ec28382c8246ab5ce3))

feat: adds support for parsing Aggregates.sort stage INTELLIJ-127

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/AddFieldsParserTest.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasAddedFields.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFieldReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt

Includes:
- Parsing of $addFields built with Aggregates.addFields, limited to, as defined in scope:
- new Field expression where the value is constant
- Autocomplete disabled when the cursor is inside addFields since at some point we would like to show warnings about possible replacement of existing fields.
- Tests for no linter warnings triggered for addFields stage

feat: add support for parsing Aggregates.addFields stage INTELLIJ-152

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/GroupStageParserTest.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt

chore: tests and minor suggestions for INTELLIJ-128

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/GroupStageParserTest.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasAccumulatedFields.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFieldReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt

feat: support for new accumulators INTELLIJ-128

---

.editorconfig
.github/workflows/draft-release.yaml
.github/workflows/publish-release.yaml
.github/workflows/quality-check.yaml

This is a general cleanup/sanitation of gha workflows. It bumps some 3rd party workflows to latest and ensures we only reference them using commit shas (per [github's recommendations](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)). Additionally, it moves our usage of the devtoolsbot user to the github app.

chore(ci): cleanup gha workflows

---

.github/workflows/check-changelog.yml
.github/workflows/quality-check.yaml

The previous check was incorrect - it was never actually running because the step name was invalid. I've moved it to a dedicated workflow because we need different triggers for the check to work correctly (e.g. it wouldn't pick up manually adding a label, because that would not trigger the workflow). I've also simplified some of the logic as we were using quite a few steps before which could be combined into a single one.

chore(ci): fix the changelog check

---

.github/workflows/quality-check.yaml
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt

Looks like the installation target is either removed or renamed and we can't install docker just with the name docker. I am using the recommended steps in Docker's [install documentation](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) to set up the install step.
For the failing test, I changed from strict version comparison to a loose comparison using `String.startsWith`. This should remove the work of keeping this number updated across different releases of mongodb server.

chore: fixes docker install step and failing build info test

---

CHANGELOG.md
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt

The key change is just around using `PsiMethodCallExpression.getVarArgsOrIterableArgs()` for resolving correct arguments, the rest of the changes are just specific tests that I added for better coverage.

fix: Filters.(and/or/nor) not working with iterable arguments for Java Driver dialect INTELLIJ-157

---

CHANGELOG.md
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaNamespaceCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/BookRepository.java
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/SpringCriteriaRepository.java
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractorTest.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationparser/AggregationParserTest.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationparser/MatchStageParserTest.kt

Adds support for parsing, inspecting and autocompleting in an aggregation written using Spring Data MongoDB. The PR mainly focuses on parsing the common syntax for writing an aggregation, using `MongoTemplate.aggregate` and `MongoTemplate.aggregateStream` and a match stage written with [Aggregation.match](https://docs.spring.io/spring-data/mongodb/reference/api/java/org/springframework/data/mongodb/core/aggregation/Aggregation.html#match(org.springframework.data.mongodb.core.aggregation.AggregationExpression):~:text=1.10-,match,-public%20static%C2%A0).

feat: add support for parsing, inspecting and autocompleting in an aggregation and a match stage written using Spring Data MongoDB INTELLIJ-172

---

CHANGELOG.md
etc/inspections.sh
etc/plugin-logs.sh
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/AbstractMongoDbInspectionBridge.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/FieldCheckInspectionBridge.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/NamespaceCheckInspectionBridge.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/InspectionStatusChangedProbe.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/CodeInsightTestExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverIndexCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverNamespaceCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/AutocompleteSuggestionAcceptedProbeTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/InspectionStatusChangedProbeTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt

feat(telemetry): Add telemetry on signals INTELLIJ-180

---

CHANGELOG.md
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/SpringCriteriaRepository.java
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/ProjectStageParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/SortStageParser.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/SortStageParserTest.kt

This PR adds support for parsing a sort stage and the commonly used variants / chains / overloads to define a sort stage and sort criteria. To check the list of supported variants please take a look at the covered test cases [here](https://github.com/mongodb/intellij/pull/123/files#diff-1973db5c1be38d28fd484fc01ddcc9256750ab6dae04654d8e911c9599233294).

feat: add support for parsing, inspecting and autocompleting in a sort stage written using Spring Data MongoDB INTELLIJ-174

---

CHANGELOG.md
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Aggregate.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Unwind.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/References.kt
packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/UnwindTest.kt

feat(query-generation): support for the unwind stages INTELLIJ-195

---

CHANGELOG.md
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Aggregate.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Sort.kt
packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/References.kt
packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/SortTest.kt

feat(query-generation): add support for $sort INTELLIJ-196

---

CHANGELOG.md
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/GroupStageParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/ProjectStageParser.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/GroupStageParserTest.kt
packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/Parser.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/HasFieldReference.kt

This PR adds support for parsing, inspecting and autocompleting in a group stage written using `Aggregation.group` and chained `GroupOperation`s using `sum`, `avg`, `first`, `last`, `max`, `min`, `push` and `addToSet`.

feat: add support for parsing, inspecting and autocompleting in a group stage written using Spring Data MongoDB INTELLIJ-175

---

.github/workflows/check-changelog.yml
.github/workflows/check-pr-title.yml
.github/workflows/publish-release.yaml
.github/workflows/quality-check.yaml

This addresses most issues reported by codeql. The remaining ones are related to using `mongodb-js/devtools-shared/actions/setup-bot-token@main` instead of pinning to a commit. I feel that this should be treated as a first-party action and be exempt from requiring commit pinning, but am open to be convinced otherwise

chore(ci): address codeql issues in gha workflows

---

CHANGELOG.md
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaMongoDbAutocompletionPopupHandlerTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/BookRepository.java
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QuerySortParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/SortStageParser.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt

This PR adds support for parsing `Sort` objects attached to `Query` objects in spring data mongodb using `.with` call.
We have re-used the entire `Sort` object parsing logic from `SortStageParser` which is why there is a little refactor over there (without any logic changes) and on top of that built a `QuerySortParser` to handle the specific cases of writing a query expression.
Test case coverage includes:
- parsing test
- field inspection test
- autocomplete test
- query generation test which was already present

feat: adds support for parsing `Sort` objects attached to `Query` objects in spring data mongodb INTELLIJ-199

---

packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProvider.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCard.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/OnlyWhenConnected.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModel.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProviderTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/insightAction/CreateSuggestedIndexInsightActionTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCardTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/OnlyWhenConnectedTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/CodeEditorViewModelTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModelTest.kt

The refactor primarily involve splitting ConnectionState.selectedConnectionState in two different attributes:
1. selectedConnection: bound to user action for selection or IDE action for restoring old selection
2. selectedConnectionState: to store sideeffects of user action such as connecting state
Also includes a few missed cases:
1. Storing the selected connection in persistent storage
2. Re-analysing on disconnect

chore: refactor for ConnectionStateViewModel

---

CHANGELOG.md
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModalTest.kt

!--
^^^^^
Please fill the title above according to https://www.conventionalcommits.org/en/v1.0.0/.
type(scope): message <TICKET-NUMBER-IF-ANY>
eg. fix(type-hint): infer type of a constant for type checking INTELLIJ-1111
-->
- Use ISO_INSTANT formatter for date formatting to include 'Z' timezone
indicator
- Keep ISO_DATE_TIME formatter for parsing to be flexible with inputs

fix: add timezone indicator to date formatting in RunQueryModal INTELLIJ-288

---

CHANGELOG.md
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModalTest.kt

- Use ISO_INSTANT formatter for date formatting to include 'Z' timezone indicator
- Keep ISO_DATE_TIME formatter for parsing to be flexible with inputs

fix: add timezone indicator to sample date formatting in RunQueryModal INTELLIJ-288

---

packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlay.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlayTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/correctness/JavaDriverMongoDbFieldDoesNotExistTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/correctness/JavaDriverMongoDbTypeMismatchTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/correctness/SpringCriteriaMongoDbFieldDoesNotExistTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/correctness/SpringCriteriaMongoDbTypeMismatchTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/environmentmismatch/JavaDriverMongoDbCollectionDoesNotExistTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/environmentmismatch/JavaDriverMongoDbNoCollectionSpecifiedTest.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/correctness/FieldDoesNotExistInspection.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/correctness/TypeMismatchInspection.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/environmentmismatch/CollectionDoesNotExistInspection.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/environmentmismatch/DatabaseDoesNotExistInspection.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexEffectivelyInspection.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspection.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/QueryInspectionTestUtils.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/correctness/FieldDoesNotExistInspectionTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/correctness/TypeMismatchInspectionTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/environmentmismatch/CollectionDoesNotExistInspectionTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/environmentmismatch/DatabaseDoesNotExistInspectionTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/environmentmismatch/NoDatabaseInferredInspectionTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspectionEffectivelyTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspectionTest.kt

- Database inspection will suppress Collection, Field, Field Type and Query inspections
- Collection inspection will suppress Field, Field Type and Query Inspections
- Field inspection will suppress Field Type inspections
Additionally we will display the Index inlay only when Namespace is available in the cluster.

fix: fixes inspection hierarchy for inspection runs INTELLIJ-293

---

packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbCompletionContributor.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverMongoDbAutocompletionPopupHandlerTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt

fix: autocomplete collections names even without an identified query INTELLIJ-124

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/environmentmismatch/JavaDriverMongoDbCollectionDoesNotExistTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/environmentmismatch/JavaDriverMongoDbDatabaseDoesNotExistTest.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt

This PR fixes the issue of only first query getting parsed in a method when there are more than one query in the same method.
The problem was that our NamespaceExtractor looks at the entire file to extract the namespace from (surrounding context) and eventually stumbles upon the method where our query is defined. Now if there are multiple queries in that method then the resolved namespace ends up being that of the first query because of [these lines here](https://github.com/mongodb/intellij/blob/main/packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt#L34-L41).
This messes up the rest of the parsing as well. This PR attempts to resolve the namespace first from within the query itself and from the resolvable elements …

fix: correctly parses Namespace when multiple queries are in the same method INTELLIJ-165

---

packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt

The API - `getDatabase` was moved to `MongoCluster` class from `MongoClient` class in a release in between `5.1.3` and 5.3.1 - latest. For that reason, we need to be checking getDatabase not just on `MongoClient` but also on `MongoCluster`.

fix: fixes namespace detection logic unable to resolve database

---

packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/correctness/JavaDriverMongoDbFieldDoesNotExistTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/correctness/JavaDriverMongoDbTypeMismatchTest.kt

Queries terminating with `.iterator` and `.cursor` calls have always been parsed and inspected for insights. The additional test cases are only to confirm the existing behaviour.
The PR adds test cases for:
1. Missing fields insight
2. Field Value type mismatch insight
and each for MongoCursor returned by a `find()` and `aggregate()` call.

chore: additional tests to verify inspections for .iterator and .cursor calls INTELLIJ-317

---

.github/workflows/pr-quality-gate.yaml
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbCompletionContributor.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlay.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionAccordion.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/AnalysisScopeViewModel.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/CodeEditorViewModel.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/InspectionsViewModel.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModalTest.kt
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/aggregationparser/AggregationParserTest.kt
packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt

Earlier we were refreshing the scope analysis on every
keystroke -> caret changes and that was causing the
CurrentQuery scope to filter out the queries on EDT
thread which is expensive because in the filter method
we use CachedQueryService.queryAt which traverses the
Psi tree, and it comes at a cost.
Now we will debounce caret changes and refresh only after
a certain time as passed which will at-least keep us from
querying CachedQueryService to a minimum during active
development.
This is still far from ideal. Ideally we should assume
that operations such as tree traversal is costly and thus
should be done suspended but that is for another commit,
perhaps. This one should remove the immediate threat for
now.

fix: removes slow EDT operation warnings collected by IntelliJ monitor when scope is set to CurrentQuery INTELLIJ-326

---

.github/workflows/act-draft-release.yaml
.github/workflows/pr-quality-gate.yaml
build.gradle.kts

verifyPlugin is a really expensive task, as it requires to download from 3 to 4 IntelliJ IDEA versions to run (around 1.5GB per IDE version) and this overloads the runners that we use during CI. Because we are running the verifyPlugin task once every day, and it's also run in the marketplace before publishing, we can get rid of it and only keep it in our scheduled nightly task.
Also, this PR makes versionBump's configuration cacheable for Gradle by removing the doLast lifecycle, which makes the task itself faster with the same behaviour (in our case).

chore: keep only verifyPlugin in the scheduled and make versionBump cacheable

---

packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlay.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/AbstractMongoDbInspectionBridge.kt
packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/performance/MongoDbQueryNotUsingFilters.kt
packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
packages/jetbrains-plugin/src/main/resources/messages/SidePanelBundle.properties
packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlayTest.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/QueryInsight.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingFiltersInspection.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexEffectivelyInspection.kt
packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspection.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingFiltersInspectionTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspectionEffectivelyTest.kt
packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspectionTest.kt

When a query has no filter, it does not make much sense for us to warn about missing or ineffective index usage. In this PR, we add another check of looking for filters in the query before running the NotUsingIndex and IneffectiveIndexUsage inspections.
Additionally, for queries that do not have any filters, we will now warn about such usage with an insight with title - "Query lacks filters, may fetch the entire collection", and also an inlay called - "No Filters"

fix: show no index warnings when a query has no filters INTELLIJ-360

---

packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Node.kt

ExplainQuery was adding HasLimit component with n=1 but when the query already had a HasLimit component (parsed from the Java code), this newly added component was getting ignored in the
DataGripMongoDbDriver.runQuery and instead of returning an object we were returning a list, which was later causing an exception in ExplainQuery itself.
I don't have a stack trace but it should be easy to reproduce by having a query with limit and letting the Index inspection run on it. The exception should be visible in debug console.
This commit fixes that by replacing the existing limit if any which should be safe to do particularly for ExplainQuery.

fix: enforce the HasLimit req by Explain
