mongodb/intellij

- CHANGELOG.md
> feat: test the new feature flow

- .github/workflows/draft-release.yaml
- .github/workflows/publish-release.yaml
- CHANGELOG.md
> chore: expose secrets in CI

- .gitignore
- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/ConnectionFailureProbe.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbe.kt
- packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MongoDbEnvironmentTestExtensions.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/ConnectionFailureProbeTest.kt
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
- packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/IntegrationTest.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfo.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfoTest.kt
> chore: send telemetry when there is a failure connecting to a cluster INTELLIJ-14

- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/MongoDbEnvironmentTestExtensions.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
- packages/mongodb-access-adapter/build.gradle.kts
- packages/mongodb-access-adapter/datagrip-access-adapter/build.gradle.kts
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriverTest.kt
- packages/mongodb-mql-model/build.gradle.kts
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/CollectionSchema.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Namespace.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Node.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasChildren.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasCollectionReference.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFieldReference.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasFilter.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/BsonTypeTest.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/CollectionSchemaTest.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NamespaceTest.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NodeTest.kt
> chore: define AST tree for the query model INTELLIJ-18

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbe.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/LogMessageTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/TelemetryServiceTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/DataGripBasedReadModelProvider.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfo.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/BuildInfoTest.kt
> chore: add atlas host to new connection events

- .github/workflows/draft-release.yaml
- packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
> fix: pipeline was not able to publish plugin INTELLIJ-39

- .github/workflows/draft-release.yaml
> chore: fix changelog on release

- packages/jetbrains-plugin/build.gradle.kts
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/i18n/Icons.kt
- packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
> chore: update plugin description

- gradle/libs.versions.toml
- packages/jetbrains-plugin/build.gradle.kts
- packages/mongodb-dialects/spring-criteria/build.gradle.kts
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialect.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- settings.gradle.kts
> chore: register new spring criteria dialect

- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/IntegrationTest.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/ModelCollectionExtractor.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/ModelCollectionExtractorTest.kt
> chore: extract collection from a model class INTELLIJ-45

- .github/workflows/quality-check.yaml
- build.gradle.kts
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/javaEditor/JavaDriverToolbarVisibilityUiTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/components/idea/IdeaFrame.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepositoryClone.java
> fix: fixes the toolbar showing up only on one file when multiple files are opened simultaneously INTELLIJ-57

- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractorTest.kt
> chore: support for finding the target collection of a spring query INTELLIJ-47

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MdbJavaEditorToolbar.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/javaEditor/JavaDriverToolbarVisibilityUiTest.kt
> chore: improve flakiness of spring criteria e2e

- CHANGELOG.md
- packages/jetbrains-plugin/build.gradle.kts
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributor.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbElementPatterns.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributor.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProvider.kt
- packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/CodeInsightTestExtensions.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/springcriteria/SpringCriteriaRepository.java
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractorTest.kt
> feat: add support for field autocompletion in spring criteria INTELLIJ-52

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/EditorToolbarDecorator.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/AbstractMongoDbInspectionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/MongoDbInspection.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/FieldCheckInspectionBridge.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchema.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListCollections.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchemaTest.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ListCollectionsTest.kt
> chore: fixed coroutine scope and failures when namespaces were not valid INTELLIJ-68

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryService.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/TelemetryEventTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/TelemetryServiceTest.kt
> chore: fix telemetry events based on conventions

- .github/workflows/draft-release.yaml
- .github/workflows/quality-check.yaml
- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbCompletionContributor.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryNamespaceInlay.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/NamespaceCheckInspectionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/quickfixes/OpenConnectionChooserQuickFix.kt
- packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
- packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverNamespaceCheckLinterInspectionTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaNamespaceCheckLinterInspectionTest.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractorTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
- packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
- packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/NamespaceCheckingLinter.kt
- packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
- packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/NamespaceCheckingLinterTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Node.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasCollectionReference.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NodeTest.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/components/HasCollectionReferenceTest.kt
> feat: warn usage of non existing databases and collections INTELLIJ-81

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
- packages/mongodb-access-adapter/datagrip-access-adapter/build.gradle.kts
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
> chore: hardcoded demo scripts

- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
> fix: concurrent access to mongosh is disallowed INTELLIJ-89

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/LogMessage.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryService.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/LogMessageTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/TelemetryServiceTest.kt
> chore: add plugin version to telemetry and logs

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
> chore: support parenthesized expressions in the java driver INTELLIJ-85

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
> fix: do not crash if we can't infer the namespace INTELLIJ-103

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
- packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
> chore: support for not in query generation INTELLIJ-77

- build.gradle.kts
> chore: fix versionBump after diktat formatting broke it

- .github/workflows/quality-check.yaml
> chore: try to cache IDEA indexes to speed up CI

- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchema.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/IntegrationTest.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
- packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
> chore: support for in and nin operators INTELLIJ-78

- .github/workflows/draft-release.yaml
- .github/workflows/publish-release.yaml
- .github/workflows/quality-check.yaml
> fix(ci): change to temurin, adopt is deprecated

- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverNamespaceCheckLinterInspectionTest.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/adt/Either.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasCollectionReference.kt
> chore: support multiple super classes in the java driver namespace extractor INTELLIJ-105

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DataSourceComboBox.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/inputs/DatabaseComboBox.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbeTest.kt
> chore: fixes for failing unit test and minor UI bug

- CHANGELOG.md
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
> feat(spring-criteria): add support for not operator INTELLIJ-61

- CHANGELOG.md
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
> feat(spring-criteria): support for in/nin operators INTELLIJ-104

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
- packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
- packages/mongodb-dialects/spring-@query/src/test/kotlin/com/mongodb/jbplugin/dialects/springquery/IntegrationTest.kt
- packages/mongodb-dialects/spring-@query/src/test/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParserTest.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/IntegrationTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasSourceDialect.kt
> feat: delegate to intellij query runner for @Query INTELLIJ-119

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
> chore: support for sessions in queries INTELLIJ-123

- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
> fix: do not throw an exception when the query is still invalid in a explain plan INTELLIJ-145

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
- packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/JavaDriverRunQueryCodeActionTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/IsCommand.kt
> feat: do not show the gutter icon for aggregates INTELLIJ-143

- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverFieldCheckLinterInspectionTest.kt
- packages/mongodb-linting-engine/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
- packages/mongodb-linting-engine/src/test/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinterTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/Parser.kt
> fix: fixes linting in nested filters

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbDataSourceService.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbe.kt
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
- packages/mongodb-access-adapter/datagrip-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriverTest.kt
> fix(ds): datasource detection considers mongodb version as a suffix in the driver name INTELLIJ-159

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/autocomplete/MongoDbCompletionContributor.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/AutocompleteSuggestionAcceptedProbe.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/AutocompleteSuggestionAcceptedProbeTest.kt
> chore: add "command" to AutocompleteGroupEvent INTELLIJ-161

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
This public method was removed from the DataGrip plugin after IDEA 2024.3.1. It should have been catched up by the plugin verifier, and we are discussing solutions already so this doesn't happen anymore.
> fix: change method removed from the datagrip plugin  INTELLIJ-171

- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/DatagripConsoleEditor.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/AutocompleteSuggestionAcceptedProbe.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/QueryRunProbe.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/CodeInsightTestExtensions.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/AutocompleteSuggestionAcceptedProbeTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/QueryRunProbeTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasSourceDialect.kt
> feat(telemetry): track when the run query button is clicked INTELLIJ-178

- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/TelemetryEvent.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/CreateIndexIntentionProbe.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/observability/probe/CreateIndexIntentionProbeTest.kt
> feat(telemetry): track when the create index intention is clicked INTELLIJ-179

- .github/workflows/codeql.yml
Cleans up codeql workflow and adds github actions scanning.
> chore(ci): update codeql workflow

- CHANGELOG.md
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/AddFields.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Aggregate.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/Project.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
- packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/aggr/AddFieldsTest.kt
> feat(query-generation): support for addFields INTELLIJ-194

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
- packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/JavaDriverIndexCheckLinterInspectionTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaIndexCheckLinterInspectionTest.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQuery.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/ExplainQueryTest.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinter.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/linting/IndexCheckingLinterTest.kt
> chore: add ineffective index usage to the index analyser INTELLIJ-216

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModalTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/AssertionExtensions.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtilTest.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/backend/MongoshBackend.kt
- packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshBackendTest.kt
- packages/mongodb-mql-model/src/docs/md/bson-type/bson-type.md
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/BsonTypeTest.kt
https://github.com/user-attachments/assets/0b8034c1-6bea-4a3b-aeb4-ea0bd5be4651
> chore: implement BsonEnum for Java enums INTELLIJ-224

- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/BuildInformation.kt
> fix(build): gracefully fail to default values if the JVM does not allow us to load the plugin metadata INTELLIJ-231

- .github/workflows/check-changelog.yml
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchema.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchemaTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/CollectionSchema.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/DataDistribution.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/DataDistributionTest.kt
> chore: adds data distribution based on sample docs in CollectionSchema INTELLIJ-214

- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/impl/IndexCheckInspectionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/DependencyInjection.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
- packages/mongodb-dialects/build.gradle.kts
- packages/mongodb-dialects/java-driver/build.gradle.kts
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
- packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
- packages/mongodb-dialects/src/main/kotlin/com/mongodb/jbplugin/dialects/Dialect.kt
- packages/mongodb-mql-engines/src/docs/md/index-analyzer/index-analyzer.md
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidation.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidationTest.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelAssertions.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/HasValueReference.kt
> feat(indexes): support for index consolidation for multiple queries in the same collection INTELLIJ-219

- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/DependencyInjection.kt
- packages/mongodb-access-adapter/src/test/kotlin/com/mongodb/jbplugin/accessadapter/slice/GetCollectionSchemaTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/aggregationstageparsers/GroupStageParserTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/ReactiveSpringCriteriaDialectParserTest.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/reactive/aggregationstageparsers/GroupStageParserTest.kt
- packages/mongodb-mql-engines/src/docs/md/index-analyzer/index-analyzer.md
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/DataDistribution.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/DataDistributionTest.kt
> feat: consider selectivity over cardinality when sorting index fields for index suggestion INTELLIJ-232

- .github/workflows/pr-quality-gate.yaml
- .github/workflows/sch-codeql.yml
> chore: run publishing serif on failures too INTELLIJ-202

- gradle/pre-commit
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelector.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/RunQueryModal.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryNamespaceInlay.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/DependencyInjection.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/CreateIndexIntentionProbe.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/QueryRunProbe.kt
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
- packages/mongodb-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/MongoDbDriver.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/query/Find.kt
- packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
- packages/mongodb-dialects/spring-@query/src/main/kotlin/com/mongodb/jbplugin/dialects/springquery/SpringAtQueryDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidation.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/FieldCheckingLinter.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
> chore: support for partialFilterExpressions in indexes INTELLIJ-227

- CHANGELOG.md
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/OrderRepository.java
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/adapter/DataGripMongoDbDriver.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/mongosh/src/main/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatter.kt
- packages/mongodb-dialects/mongosh/src/test/kotlin/com/mongodb/jbplugin/dialects/mongosh/MongoshDialectFormatterTest.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidation.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzer.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/indexing/IndexQueryFieldUsage.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/CollectionIndexConsolidationTest.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/indexing/IndexAnalyzerTest.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelAssertions.kt
- packages/mongodb-mql-engines/src/test/kotlin/com/mongodb/jbplugin/utils/ModelDsl.kt
> chore: support for partialFilterExpression in the index consolidation INTELLIJ-223

- build.gradle.kts
> chore: qodana should not block a release

- .github/workflows/act-draft-release.yaml
- buildSrc/src/main/kotlin/com.mongodb.intellij.isolated-module.gradle.kts
> chore: verify plugin now requires the segment api key

- CHANGELOG.md
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
> fix(java): ability to parse .iterator queries written in the MongoDB java driver INTELLIJ-235

- buildSrc/build.gradle.kts
- gradle/libs.versions.toml
- packages/jetbrains-plugin/build.gradle.kts
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/SidePanel.kt
- packages/jetbrains-plugin/src/main/resources/META-INF/plugin.xml
> chore: Add empty panel for MongoDB INTELLIJ-237

- CHANGELOG.md
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatter.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectFormatterTest.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/BsonType.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/BsonTypeTest.kt
> fix(schema): ensure valid cardinality for empty BsonAnyOf types INTELLIJ-236

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/MdbEditorService.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/settings/PluginSettings.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/settings/PluginSettingsConfigurable.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/SidePanel.kt
- packages/jetbrains-plugin/src/main/resources/messages/SettingsBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/settings/PluginSettingsTest.kt
> chore: Add feature toggle to switch between the new side panel and the toolbar INTELLIJ-238

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModel.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/ConnectionPreferences.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/services/implementations/PersistentConnectionPreferences.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModel.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/editor/models/ToolbarModelTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModelTest.kt
> chore: restore the previously selected data source INTELLIJ-273

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProvider.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCard.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/DatabaseComboBox.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModel.kt
- packages/jetbrains-plugin/src/main/resources/messages/SidePanelBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaMongoDbAutocompletionPopupHandlerTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaFieldCheckLinterInspectionTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/impl/SpringCriteriaNamespaceCheckLinterInspectionTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCardTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/DatabaseComboBoxTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModelTest.kt
- Adds the DatabaseComboBox which will always be visible in the SidePanel
- The value selected in the DatabaseComboBox is taken into consideration only when the inferred dialect is Spring related dialect (changes in MongoDBVirtualDataSourceProvider)
https://github.com/user-attachments/assets/14666d11-3d12-4a50-846b-4786d557117c
> feat: added DatabaseComboBox for spring related dialect INTELLIJ-258

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/AbstractMongoDbInspectionBridgeV2.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/analysisScope/AnalysisScope.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/quickfixes/LocalQuickFixBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/meta/CoroutinesEx.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionAccordion.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionScopeSettings.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/AnalysisScopeViewModel.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/CodeEditorViewModel.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/InspectionsViewModel.kt
- packages/jetbrains-plugin/src/main/resources/messages/SidePanelBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/analysisScope/AnalysisScopeTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/meta/CoroutinesExTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionScopeSettingsTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/AnalysisScopeViewModelTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/InspectionsViewModelTest.kt
> chore: support for a new scope: AllInsights INTELLIJ-281

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/analysisScope/AnalysisScope.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionScopeSettings.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/AnalysisScopeViewModel.kt
- packages/jetbrains-plugin/src/main/resources/messages/SidePanelBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inspections/analysisScope/AnalysisScopeTest.kt
> chore: new recommended insights scope INTELLIJ-284

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/analysisScope/AnalysisScope.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionAccordion.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionScopeSettings.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/AnalysisScopeViewModel.kt
- packages/jetbrains-plugin/src/main/resources/messages/SidePanelBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionAccordionTest.kt
> chore: add empty state for insights INTELLIJ-285

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/MongoDbVirtualFileDataSourceProvider.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCard.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/CodeEditorViewModel.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/fixtures/IntegrationTestExtensions.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCardTest.kt
Includes:
- Corrected visibility of DatabaseComboBox. We will show DatabaseComboBox now only when at-least one of the identified dialect requires the database selection.
> chore: corrects the visibility of DatabaseComboBox INTELLIJ-291

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModel.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/InspectionsViewModel.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModelTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/InspectionsViewModelTest.kt
> fix: remove insights when changing connections INTELLIJ-302

- .github/workflows/act-draft-release.yaml
- .github/workflows/pr-quality-gate.yaml
- buildSrc/src/main/kotlin/com.mongodb.intellij.plugin-component.gradle.kts
- gradle/libs.versions.toml
> chore: update max version to latest 251

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtilTest.kt
> fix(java-parser): support for string concatenation INTELLIJ-116

- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexEffectivelyInspection.kt
- packages/mongodb-mql-engines/src/main/kotlin/com/mongodb/jbplugin/linting/performance/QueryNotUsingIndexInspection.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/IsCommand.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/components/IsCommandTest.kt
> chore: do not run index suggestions on queries that won't use indexes INTELLIJ-299

- packages/jetbrains-plugin/src/main/resources/messages/CodeActionsBundle.properties
- packages/jetbrains-plugin/src/main/resources/messages/InspectionsAndInlaysBundle.properties
- packages/jetbrains-plugin/src/main/resources/messages/MdbToolbarBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlayTest.kt
> chore: fix some labels and clean up INTELLIJ-297

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlay.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionAccordion.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/InspectionsViewModel.kt
> chore: open performance category when opening the side panel through the inlay INTELLIJ-300

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt
> chore: fix issue when methods refer to non existing classes or interfaces INTELLIJ-305

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/AbstractMongoDbCodeActionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/MongoDbCodeAction.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/RunQueryCodeActionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inlays/MongoDbQueryIndexStatusInlay.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/AbstractMongoDbInspectionBridgeV2.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/JavaDriverRunQueryCodeActionTest.kt
- packages/jetbrains-plugin/src/test/resources/project-fixtures/basic-java-project-with-mongodb/src/main/java/alt/mongodb/javadriver/JavaDriverRepository.java
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/Node.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/IsCommand.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/components/Named.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/Parser.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/IsCommand.kt
- packages/mongodb-mql-model/src/main/kotlin/com/mongodb/jbplugin/mql/parser/components/Named.kt
- packages/mongodb-mql-model/src/test/kotlin/com/mongodb/jbplugin/mql/NodeTest.kt
> fix: disable actions on queries with unsupported features INTELLIJ-301

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModel.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModelTest.kt
> chore: reanalyse scope when connected INTELLIJ-307

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCard.kt
- packages/jetbrains-plugin/src/main/resources/messages/SidePanelBundle.properties
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCardTest.kt
> chore: add new connection option in combobox INTELLIJ-306

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCard.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/DatabaseComboBox.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionScopeSettings.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/utilities/ControlledComboBox.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/ConnectionBootstrapCardTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/DatabaseComboBoxTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/inspections/InspectionScopeSettingsTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/utilities/ControlledComboBoxTest.kt
> fix: dismiss the ControlledComboBox on selection INTELLIJ-309

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelector.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/inspections/AbstractMongoDbInspectionBridge.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/ConnectionFailureProbe.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/observability/probe/NewConnectionActivatedProbe.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/viewModel/ConnectionStateViewModel.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelectorTest.kt
- packages/mongodb-access-adapter/datagrip-access-adapter/src/main/kotlin/com/mongodb/jbplugin/accessadapter/datagrip/DataGripBasedReadModelProvider.kt
> fix: fixes the failing null assertion in CachedQueryService INTELLIJ-314

- .github/workflows/act-draft-release.yaml
- .github/workflows/act-publish-release.yaml
- .github/workflows/pr-metadata-verification.yaml
- .github/workflows/pr-quality-gate.yaml
- .github/workflows/sch-codeql.yml
- .github/workflows/sch-verify-latest-ide-version.yml
- CODEOWNERS
- build.gradle.kts
- buildSrc/src/main/kotlin/com.mongodb.intellij.isolated-module.gradle.kts
- buildSrc/src/main/kotlin/com.mongodb.intellij.plugin-component.gradle.kts
- buildSrc/src/main/kotlin/com/mongodb/intellij/CheckSpecUpdatesTask.kt
- buildSrc/src/main/kotlin/com/mongodb/intellij/GitHubHelper.kt
- buildSrc/src/main/kotlin/com/mongodb/intellij/JIRAHelper.kt
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
> chore: ensure that next idea versions are compatible INTELLIJ-312

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelector.kt
Running the events in EDT didn't work because it was waiting for the EDT to be available, and the modal blocks it.
> fix(modal): databases were not loading in the run query modal INTELLIJ-340

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/JavaDriverCompletionContributorTest.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/autocomplete/SpringCriteriaCompletionContributorTest.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/PsiMdbTreeUtil.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParserTest.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/QueryTargetCollectionExtractor.kt
- packages/mongodb-dialects/spring-criteria/src/main/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParser.kt
- packages/mongodb-dialects/spring-criteria/src/test/kotlin/com/mongodb/jbplugin/dialects/springcriteria/SpringCriteriaDialectParserTest.kt
> chore: add support for queries in variables INTELLIJ-335

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/codeActions/impl/runQuery/NamespaceSelector.kt
- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/editor/CachedQueryService.kt
> fix: Namespace selector will not show wrong collections from previous database selection INTELLIJ-353

- README.md
> chore: fix README.md links to images

- README.md
> chore: add labels to README.md

- packages/jetbrains-plugin/src/main/kotlin/com/mongodb/jbplugin/ui/components/connection/OnlyWhenConnected.kt
- packages/jetbrains-plugin/src/test/kotlin/com/mongodb/jbplugin/ui/components/connection/OnlyWhenConnectedTest.kt
> fix: remove CircularProgress to allow IntelliJ to close INTELLIJ-354

- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/JavaDriverDialectParser.kt
- packages/mongodb-dialects/java-driver/src/main/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractor.kt
- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt
> fix: consider query method as namespace resolution candidate INTELLIJ-359

- CODEOWNERS
- README.md
> chore: make images png and fix CODEOWNERS INTELLIJ-289

- README.md
> chore: clean up a bit the README.md

- .github/workflows/act-publish-release.yaml
> chore: fix ga release

- .github/workflows/act-publish-release.yaml
- README.md
> fix: README pointing to the wrong repository

- packages/mongodb-dialects/java-driver/src/test/kotlin/com/mongodb/jbplugin/dialects/javadriver/glossary/NamespaceExtractorTest.kt
> chore: adds additional tests for NamespaceExtractor
